yii1114/demos/tbsi-skincare/protected/controllers/HelpController.php
<?php

class HelpController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions'=>array('page'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This method is invoked right before an action is to be executed (after all possible filters.)
	 * You may override this method to do last-minute preparation for the action.
	 * @param CAction $action the action to be executed.
	 * @return boolean whether the action should be executed.
	 */
	public function beforeAction($action)
	{
		$this->menu=array(
			array('label'=>_('About This CMS'), 'url'=>array('help/page','view'=>'index')),
			array('label'=>_('Getting Started'), 'url'=>array('help/page','view'=>'gettingstarted')),
			array('label'=>_('Localisation'), 'url'=>array('help/page','view'=>'localisation')),
			array('label'=>'<hr style="margin: 0;" />'),
			array('label'=>_('Managing Products'), 'url'=>array('help/page','view'=>'managingproducts'), 'items'=>array(
				array('label'=>_('Searching Products'), 'url'=>array('help/page','view'=>'searchingproducts')),
				array('label'=>_('Adding Products'), 'url'=>array('help/page','view'=>'creatingproducts')),
				array('label'=>_('Updating Products'), 'url'=>array('help/page','view'=>'updatingproducts')),
				array('label'=>_('Deleting Products'), 'url'=>array('help/page','view'=>'deletingproducts')),
				array('label'=>'<hr style="margin: 0;" />'),
				array('label'=>_('Bulk Upload'), 'url'=>array('help/page','view'=>'bulkupload')),
				array('label'=>_('Scraping Price & Stock'), 'url'=>array('help/page','view'=>'scrapepricestock')),
			)),
			array('label'=>'<hr style="margin: 0;" />'),
			array('label'=>_('Product Variants'), 'url'=>array('help/page','view'=>'productvariants'), 'items'=>array(
				array('label'=>_('Adding Product Variants'), 'url'=>array('help/page','view'=>'creatingproductvariants')),
				array('label'=>_('Updating Product Variants'), 'url'=>array('help/page','view'=>'updatingproductvariants')),
				array('label'=>_('Deleting Product Variants'), 'url'=>array('help/page','view'=>'deletingproductvariants')),
			)),
			array('label'=>'<hr style="margin: 0;" />'),
			array('label'=>_('Product Ranges'), 'url'=>array('help/page','view'=>'productranges'), 'items'=>array(
				array('label'=>_('Adding Product Ranges'), 'url'=>array('help/page','view'=>'creatingproductranges')),
				array('label'=>_('Updating Product Ranges'), 'url'=>array('help/page','view'=>'updatingproductranges')),
			)),
			array('label'=>'<hr style="margin: 0;" />'),
			array('label'=>_('Product Tags'), 'url'=>array('help/page','view'=>'producttags'), 'items'=>array(
				array('label'=>_('Adding Product Tags'), 'url'=>array('help/page','view'=>'creatingproducttags')),
				array('label'=>_('Updating Product Tags'), 'url'=>array('help/page','view'=>'updatingproducttags')),
			)),
			array('label'=>'<hr style="margin: 0;" />'),
			array('label'=>_('Managing Quizzes'), 'url'=>array('help/page','view'=>'managingquizzes'), 'items'=>array(
				array('label'=>_('Adding Quizzes'), 'url'=>array('help/page','view'=>'creatingquizzes')),
				array('label'=>_('Updating Quizzes'), 'url'=>array('help/page','view'=>'updatingquizzes')),
			)),
			array('label'=>'<hr style="margin: 0;" />'),
			array('label'=>_(' Questions'), 'url'=>array('help/page','view'=>'questions'), 'items'=>array(
				array('label'=>_('Adding Questions'), 'url'=>array('help/page','view'=>'creatingquestions')),
				array('label'=>_('Updating Questions'), 'url'=>array('help/page','view'=>'updatingquestions')),
				array('label'=>_('Deleting Questions'), 'url'=>array('help/page','view'=>'deletingquestions')),
			)),
			array('label'=>'<hr style="margin: 0;" />'),
			array('label'=>_(' Answers'), 'url'=>array('help/page','view'=>'answers'), 'items'=>array(
				array('label'=>_('Adding Answers'), 'url'=>array('help/page','view'=>'creatinganswers')),
				array('label'=>_('Updating Answers'), 'url'=>array('help/page','view'=>'updatinganswers')),
				array('label'=>_('Deleting Answers'), 'url'=>array('help/page','view'=>'deletinganswers')),
			)),
			array('label'=>'<hr style="margin: 0;" />'),
			array('label'=>_(' Related Products'), 'url'=>array('help/page','view'=>'relatedproducts'), 'items'=>array(
				array('label'=>_('Updating Related Products'), 'url'=>array('help/page','view'=>'updatingrelatedproducts')),
				array('label'=>_('Deleting Related Products'), 'url'=>array('help/page','view'=>'deletingrelatedproducts')),
			)),
		);

		return parent::beforeAction($action);
	}
}

yii1114/demos/tbsi-skincare/protected/controllers/QuizController.php
<?php

class QuizController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions'=>array('view','create','update','admin','delete'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$questionModel=new Question('search');
		$questionModel->unsetAttributes();  // clear any default values
		$questionModel->quizId=$id;

		$this->render('view',array(
			'model'=>$this->loadModel($id),
			'questionModel'=>$questionModel,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Quiz;

		if(isset($_POST['Quiz']))
		{
			$model->attributes=$_POST['Quiz'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		if(isset($_POST['Quiz']))
		{
			$model->attributes=$_POST['Quiz'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Quiz('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Quiz']))
			$model->attributes=$_GET['Quiz'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Quiz the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Quiz::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
}

yii1114/demos/tbsi-skincare/protected/controllers/TagController.php
<?php

class TagController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions'=>array('view','create','update','admin'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Tag;

		if(isset($_POST['Tag']))
		{
			$model->attributes=$_POST['Tag'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		if(isset($_POST['Tag']))
		{
			$model->attributes=$_POST['Tag'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Tag('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Tag']))
			$model->attributes=$_GET['Tag'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Tag the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Tag::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
}

yii1114/demos/tbsi-skincare/protected/views/help/pages/answers.php
<?php

$this->breadcrumbs=array(
	_('Help')=>array('help/page','view'=>'index'),
	_('Answers')
);

?>

<h1><?php echo _('Answers'); ?></h1>

<p><?php echo sprintf(_('To view answers, first find a question list (see <a href="%s">Questions</a>).'), $this->createUrl('help/page',array('view'=>'questions'))); ?></p>
<p><?php echo sprintf(_('Then click the %s icon next to the question you want view answers to.'), '<img src="'.Yii::app()->baseUrl.'/images/blueprint/view.png" alt="" />'); ?></p>

<p><?php echo _('Answers can be reordered by dragging rows in the grid up and down. Answers will be displayed in the order they are listed.'); ?></p>

yii1114/demos/tbsi-skincare/protected/views/help/pages/creatingproducts.php
<?php

$this->breadcrumbs=array(
	_('Help')=>array('help/page','view'=>'index'),
	_('Managing Products')=>array('help/page','view'=>'managingproducts'),
	_('Adding Products')
);

?>

<h1><?php echo _('Adding Products'); ?></h1>

<p><?php echo _('To add a new product, click the "Products" link in the main menu at the top of the screen, then click the "Create Product" link in the "Operations" menu to the right of the screen.'); ?></p>
<p><?php echo _('Alternatively, follow the link below.'); ?></p>
<p><a href="<?php echo $this->createUrl('product/create'); ?>"><?php echo $this->createAbsoluteUrl('product/create'); ?></a></p>

<br />

<ul>
	<li><?php echo _('Complete the form to add a new product.'); ?></li>
	<li><?php echo sprintf(_('The "Product Range" will be shown on the results page to help visually separate products. For more information, see <a href="%s">Product Ranges</a>.'), $this->createUrl('help/page',array('view'=>'productranges'))); ?></li>
	<li><?php echo sprintf(_('The "Product Tag" is used to create a regime on the results page (i.e. cleanse, tone, moisturise). For more information, see <a href="%s">Product Tags</a>.'), $this->createUrl('help/page',array('view'=>'producttags'))); ?></li>
	<li><?php echo _('It is important you enter the "Product Code" accurately as this is used to retrieve image, stock and price information.'); ?></li>
	<li><?php echo _('Product "Name", "Best Seller", "Details" and "Detail Bullets" will be displayed on the results page. Enter a pipe "|" to separate each bullet point.'); ?></li>
	<li><?php echo _('You must enter a "Gender" and a "Day/Night" value. This will help the tool correctly allocate the products it recommends.'); ?></li>
	<li><?php echo _('You can set a product "Status" to "Active" or "Inactive". Inactive products (including all product variants) will not show up on the results page.'); ?></li>
</ul>

yii1114/demos/tbsi-skincare/protected/views/help/pages/creatingproducttags.php
<?php

$this->breadcrumbs=array(
	_('Help')=>array('help/page','view'=>'index'),
	_('Product Tags')=>array('help/page','view'=>'producttags'),
	_('Adding Product Tags')
);

?>

<h1><?php echo _('Adding Product Tags'); ?></h1>

<p><?php echo _('To add a new product tag, click the "Products" link in the main menu at the top of the screen, then click the "Manage Product Tags" then "Create Product Tag" links in the "Operations" menu to the right of the screen.'); ?></p>
<p><?php echo _('Alternatively, follow the link below.'); ?></p>
<p><a href="<?php echo $this->createUrl('tag/create'); ?>"><?php echo $this->createAbsoluteUrl('tag/create'); ?></a></p>

<br />

<ul>
	<li><?php echo _('Complete the form to add a new product tag.'); ?></li>
	<li><?php echo _('The "Name" will be displayed on the results page.'); ?></li>
</ul>

yii1114/demos/tbsi-skincare/protected/views/help/pages/creatingproductvariants.php
<?php

$this->breadcrumbs=array(
	_('Help')=>array('help/page','view'=>'index'),
	_('Product Variants')=>array('help/page','view'=>'productvariants'),
	_('Adding Product Variants')
);

?>

<h1><?php echo _('Adding Product Variants'); ?></h1>

<p><?php echo _('To add a new product variant from a product screen, click "Create Product Variant" in the "Operations" menu to the right of the screen.'); ?></p>

<br />

<ul>
	<li><?php echo _('Complete the form to add a new product variant.'); ?></li>
	<li><?php echo _('It is important you enter the "Code" accurately as this is used to retrieve stock and price information.'); ?></li>
	<li><?php echo _('The "Name" will be displayed alongside the price on the results screen so the user knows what they are purchasing.'); ?></li>
	<p><?php echo sprintf(_('Price and stock information will be retrieved automatically. For more information, see <a href="%s">Scraping Price & Stock</a>.'), $this->createUrl('help/page',array('view'=>'scrapepricestock'))); ?></p>
	<li><?php echo _('You can set a product variant "Status" to "Active" or "Inactive". Inactive product variants will not show up on the results page.'); ?></li>
</ul>

yii1114/demos/tbsi-skincare/protected/views/help/pages/creatingquestions.php
<?php

$this->breadcrumbs=array(
	_('Help')=>array('help/page','view'=>'index'),
	_('Questions')=>array('help/page','view'=>'questions'),
	_('Adding Questions'),
);

?>

<h1><?php echo _('Adding Questions'); ?></h1>

<p><?php echo sprintf(_('To add a new question, first find a question list (see <a href="%s">Questions</a>).'), $this->createUrl('help/page',array('view'=>'questions'))); ?></p>
<p><?php echo _('Then click the "Add Question" link in the "Operations" menu to the right of the screen.'); ?></p>

<br />

<ul>
	<li><?php echo _('Complete the form to add a new question.'); ?></li>
	<li><?php echo _('The "Type" of the question can be "Single-select" or "Multiple-select".'); ?></li>
	<li><?php echo _('If you choose multiple-select, you must also choose the minimum number of selections the user must make to proceed.'); ?></li>
	<li><?php echo _('The "Title" and "Text" will be displayed at the top of the question screen to pose the question to the user.'); ?></li>
	<li><?php echo _('The "Did You Know" will be displayed to the right of the screen for factual information related to the question.'); ?></li>
	<li><?php echo _('The "Breadcrumb" is the text shown in the progress bar at the bottom of the screen. If you do not check "Show Breadcrumb", then the question will not appear in the progress bar.'); ?></li>
	<li><?php echo sprintf(_('If you enter "Summary Text" then this will show on the summary page when the user completes the quiz. You can use the code %s to show the given answer.'), htmlentities('<span>%s</span>')); ?></li>
	<li><?php echo _('You can set a quiz "Status" to "Active" or "Inactive".'); ?></li>
</ul>

<p>
	<strong><?php echo _('An example of summary text:'); ?></strong>
	<?php echo sprintf(_('You have chosen %s.'), htmlentities('<span>%s</span>')); ?>
</p>

<p><?php echo _('If the user chooses "Oily Skin", on the summary page the above text would show "You have chosen Oily Skin".'); ?></p>

yii1114/demos/tbsi-skincare/protected/views/help/pages/creatingquizzes.php
<?php

$this->breadcrumbs=array(
	_('Help')=>array('help/page','view'=>'index'),
	_('Managing Quizzes')=>array('help/page','view'=>'managingquizzes'),
	_('Adding Quizzes'),
);

?>

<h1><?php echo _('Adding Quizzes'); ?></h1>

<p><?php echo _('To add a new quiz, click the "Quizzes" link in the main menu at the top of the screen, then click the "Create Quiz" link in the "Operations" menu to the right of the screen.'); ?></p>
<p><?php echo _('Alternatively, follow the link below.'); ?></p>
<p><a href="<?php echo $this->createUrl('quiz/create'); ?>"><?php echo $this->createAbsoluteUrl('quiz/create'); ?></a></p>

<br />

<ul>
	<li><?php echo _('Complete the form to add a new quiz.'); ?></li>
	<li><?php echo _('It is important that there are only 4 active quizzes at any one time: Female Express, Female Complete, Male Express and Male Complete'); ?></li>
	<li><?php echo _('You can set a quiz "Status" to "Active" or "Inactive".'); ?></li>
</ul>

yii1114/demos/tbsi-skincare/protected/views/help/pages/deletingquestions.php
<?php

$this->breadcrumbs=array(
	_('Help')=>array('help/page','view'=>'index'),
	_('Questions')=>array('help/page','view'=>'questions'),
	_('Deleting Questions'),
);

?>

<h1><?php echo _('Deleting Questions'); ?></h1>

<p><?php echo sprintf(_('To delete a question, first find a question list (see <a href="%s">Questions</a>).'), $this->createUrl('help/page',array('view'=>'questions'))); ?></p>
<p><?php echo sprintf(_('Then click the %s icon next to the question you want to delete.'), '<img src="'.Yii::app()->baseUrl.'/images/blueprint/delete.png" alt="" />'); ?></p>

<br />

<ul>
	<li><?php echo _('You will be prompted to confirm your actions.'); ?></li>
	<li><?php echo _('Deleting is irreversible.'); ?></li>
	<li><?php echo _('The question (including all answers and related product weights) will be deleted.'); ?></li>
</ul>

yii1114/demos/tbsi-skincare/protected/views/help/pages/gettingstarted.php
<?php

$this->breadcrumbs=array(
	_('Help')=>array('help/page','view'=>'index'),
	_('Getting Started')
);

?>

<h1><?php echo _('Getting Started'); ?></h1>

<p><?php echo _('This help section provides information on every screen within the CMS. If you are ever stuck on a specific screen, or you need information on how to perform an action, you should be able to find a relevant article from the "Operations" menu in this help section.'); ?></p>

<p><?php echo _('This Getting Started guide aims to direct you to the key articles within the help section to cover the basic familiarisation of the CMS.'); ?></p>

<ul>
	<li>
		<strong><?php echo _('For populating the CMS for the first time via a CSV export'); ?><br /></strong>
		<em><?php echo _('See'); ?></em> <a href="<?php echo $this->createUrl('help/page',array('view'=>'bulkupload')); ?>"><?php echo _('Bulk Upload'); ?></a>
	</li>
	<li>
		<strong><?php echo _('For information on managing products and product variants'); ?><br /></strong>
		<em><?php echo _('See'); ?></em> <a href="<?php echo $this->createUrl('help/page',array('view'=>'managingproducts')); ?>"><?php echo _('Managing Products'); ?></a>
	</li>
	<li>
		<strong><?php echo _('For information on managing quizzes, questions and answers'); ?><br /></strong>
		<em><?php echo _('See'); ?></em> <a href="<?php echo $this->createUrl('help/page',array('view'=>'managingquizzes')); ?>"><?php echo _('Managing Quizzes'); ?></a>
	</li>
	<li>
		<strong><?php echo _('To better understand how the tool works to select relevant products'); ?><br /></strong>
		<em><?php echo _('See'); ?></em> <a href="<?php echo $this->createUrl('help/page',array('view'=>'relatedproducts')); ?>"><?php echo _('Related Products'); ?></a>
	</li>
	<li>
		<strong><?php echo _('For information on localisation'); ?><br /></strong>
		<em><?php echo _('See'); ?></em> <a href="<?php echo $this->createUrl('help/page',array('view'=>'localisation')); ?>"><?php echo _('Localisation'); ?></a>
	</li>
</ul>

yii1114/demos/tbsi-skincare/protected/views/help/pages/index.php
<?php

$this->breadcrumbs=array(
	_('Help'),
);

?>

<h1><?php echo _('About This CMS'); ?></h1>

<p><?php echo _('This CMS can be used to manage the online skincare diagnostic tool for the Body Shop.'); ?></p>
<p><?php echo _('The CMS can be broken down in to 2 top-level functions.'); ?></p>

<ul>
	<li><?php echo _('Management of products.'); ?></li>
	<li><?php echo _('Management of quizzes.'); ?></li>
</ul>

<p><?php echo _('When using the CMS, please take note of the following conventions.'); ?></p>

<ul>
	<li><?php echo _('Navigate between managing products and quizzes using the main menu bar at the top of the screen.'); ?></li>
	<li><?php echo _('When managing products or quizzes, you will have the option to create new data, update existing data and delete old data. Links to these options, as well as other options, can always be found in the "Operations" menu to the right of the screen.'); ?></li>
	<li><?php echo _('You can always check your current position in the CMS by following the "breadcrumb" trail which is shown directly underneath the main menu bar at the top of the screen'); ?></li>
	<li><?php echo _('Where there are "lists" of data, the CMS will always display the data in a grid. Use the fields at the top of the grid to search and filter the data. Use the page numbers at the bottom of the grid to browse through the data.'); ?></li>
	<li><?php echo sprintf(_('When working with grids, you can use the icons in the right-most column to view %s, edit %s or delete %s the current row.'), '<img src="'.Yii::app()->baseUrl.'/images/blueprint/view.png" alt="" />', '<img src="'.Yii::app()->baseUrl.'/images/blueprint/update.png" alt="" />', '<img src="'.Yii::app()->baseUrl.'/images/blueprint/delete.png" alt="" />'); ?></li>
	<li><?php echo sprintf(_('Some grids allow for sorting of data. If when you hover over a grid you see the %s icon, you can click and drag rows up and down to reorder the data.'), '<img src="'.Yii::app()->baseUrl.'/images/blueprint/move.gif" alt="" />'); ?></li>
</ul>

<p>
	<strong><?php echo _('An example of grid data:'); ?></strong><br />
	<img src="<?php echo Yii::app()->baseUrl; ?>/images/blueprint/screenshot.png" alt="" />
</p>

yii1114/demos/tbsi-skincare/protected/views/help/pages/productranges.php
<?php

$this->breadcrumbs=array(
	_('Help')=>array('help/page','view'=>'index'),
	_('Product Ranges')
);

?>

<h1><?php echo _('Product Ranges'); ?></h1>

<p><?php echo _('To manage product ranges, click the "Products" link in the main menu at the top of the screen, then click the "Manage Product Ranges" link in the "Operations" menu to the right of the screen.'); ?></p>
<p><?php echo _('Alternatively, follow the link below.'); ?></p>
<p><a href="<?php echo $this->createUrl('productrange/admin'); ?>"><?php echo $this->createAbsoluteUrl('productrange/admin'); ?></a></p>

<br />

<ul>
	<li><?php echo _('Product ranges are used to categorise products. They are shown on the results page to help visually separate products.'); ?></li>
	<li><?php echo _('Product ranges are managed separately to products. A new product range must be created before creating the products that go in it. Updating an existing product range will affect all associated products.'); ?></li>
	<li><?php echo _('Product ranges cannot be deleted.'); ?></li>
</ul>

yii1114/demos/tbsi-skincare/protected/views/help/pages/producttags.php
<?php

$this->breadcrumbs=array(
	_('Help')=>array('help/page','view'=>'index'),
	_('Product Tags')
);

?>

<h1><?php echo _('Product Tags'); ?></h1>

<p><?php echo _('To manage product tags, click the "Products" link in the main menu at the top of the screen, then click the "Manage Product Tags" link in the "Operations" menu to the right of the screen.'); ?></p>
<p><?php echo _('Alternatively, follow the link below.'); ?></p>
<p><a href="<?php echo $this->createUrl('tag/admin'); ?>"><?php echo $this->createAbsoluteUrl('tag/admin'); ?></a></p>

<br />

<ul>
	<li><?php echo _('At all times, there must be Cleanse, Tone and Moisturise tags. These are special tags which form the basis to build a regime on the results page.'); ?></li>
	<li><?php echo _('Product tags are managed separately to products. A new product tag must be created before creating the products that go in it. Updating an existing product tag will affect all associated products.'); ?></li>
	<li><?php echo _('Product tags cannot be deleted.'); ?></li>
</ul>